Switch to pathlib
bakfile/bak-python pull request #44
Opened 2021-01-27 00:13 UTC by Serene-Arc

Commit moving the program to using the `pathlib` library as per the discussion in #25

2021-01-27 02:18 UTC, ChanceNCounter requested changes

2021-01-27 02:18 UTC, ChanceNCounter commented on bak/commands/__init__.py
> +                                    filename.resolve(),
Looks great, overall! I especially appreciate that you hit the spaghetti that hit you. Long way to go there, but it's nice when people touch it up rather than powering through it.

This bit seems to be clobbering the bakfile name. Also needs to `expanduser`. For reference, having cloned the repo on a Mac, this is the original result when you `bak ~/bak/foo.txt`:

`Users-Chance-bak-foo.txt.1611713628-948247.bak`

and here's the bugged result:

`.sers.hance.ak-foo.txt.1611712778-679439.bak`

2021-01-27 03:28 UTC, Serene-Arc commented on bak/commands/__init__.py
> +                                    filename.resolve(),
There's a whole bunch of things that my IDE (PyCharm) suggests, like unused imports, and some PEP8 things but I didn't want to force them on your code for no reason since, for the most part, they're just stylistic and that seems rude. I thought that particular part of determining the filename could be a lot simpler with `pathlib` since you can access the file path attributes directly rather than using indexes and slicing, but it seems outside the scope of this pull request and something that should really have a testing suite covering it.

Which is the cause of this bug, actually. Sorry I didn't catch it, but one of the slices is a bit overzealous, which I'm guessing is from a difference in how `os` and `pathlib` output lists of path parts i.e. with or without a leading slash. So I did end up having to rewrite it a little.

Also, all resolving and user tilde expansion is now done at the cli-command stage in `__main__.py` so this part of the file basically always assumes that the path passed in is properly resolved.

2021-01-27 04:00 UTC, ChanceNCounter commented on bak/commands/__init__.py
> +                                    filename.resolve(),
Fair enough. And, fwiw, the thing is supposed to get a PEP8 kiss every time I save. I forgot to set it up in my editor for this project. That'll be my next commit, I guess =P

As for writing bugs, that's life! Code review's good, tests will be better.

2021-01-27 04:20 UTC, Serene-Arc commented on bak/commands/__init__.py
> +                                    filename.resolve(),
PEP8 isn't a big deal, it's just not something that I wanted to do because it's a whole lot of tiny changes that seem a lot in a git diff, just spacing and stuff. My save does that as well :) Though I set it to a max line length of 120 instead of 80 because 80 is stupid. 

If you'd like I can submit a few more commits with some cleanup stuff

2021-01-27 07:56 UTC, ChanceNCounter commented on bak/commands/__init__.py
> +                                    filename.resolve(),
I'll hit it with pep8 and pylint once I'm done merging stuff.

This looks like it's working now. Obligatory "leave nontrivial PRs overnight and retest."

2021-01-27 08:02 UTC, Serene-Arc commented on bak/commands/__init__.py
> +                                    filename.resolve(),
Sounds good

2021-01-28 00:40 UTC, ChanceNCounter approved these changes

2021-01-28 00:52 UTC, ChanceNCounter commented
Seems to be in order. I couldn't break it, anyway. Thanks very much for contributing!

Rebased to squash because GitHub's squash button clobbers authorship :( I really hate that it does that, force-pushing to somebody else's fork always feels a little weird even if it's in the workflow.

2021-01-28 00:52 UTC, merged